"""add lookup table

Revision ID: 2cf857ce9cfc
Revises: c464bf0ce39b
Create Date: 2022-02-06 10:09:40.812355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf857ce9cfc'
down_revision = 'c464bf0ce39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookup',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('response_code', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_ip_address'), 'lookup', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lookup_ip_address'), table_name='lookup')
    op.drop_table('lookup')
    # ### end Alembic commands ###
